### ISSUE TITLE
抢沙发,启动崩溃

### ISSUE THREAD

**Issue by luxiao0314** [TeamNB/FakeBiliBili#1]
java.lang.IllegalStateException: Required view 'iv_load_failed' with ID 2131689739 for field 'ivLoadFailed' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
                                                                  at butterknife.internal.Utils.findRequiredView(Utils.java:92)
                                                                  at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:104)
                                                                  at com.bilibili.widget.adapter.binder.BiliLoadFailedBinder$LoadFailedHolder_ViewBinding.<init>(BiliLoadFailedBinder$LoadFailedHolder_ViewBinding.java:23)
                                                                  at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                  at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
                                                                  at butterknife.ButterKnife.bind(ButterKnife.java:172)
                                                                  at com.bilibili.widget.adapter.binder.BiliLoadFailedBinder$LoadFailedHolder.<init>(BiliLoadFailedBinder.java:65)
                                                                  at com.bilibili.widget.adapter.binder.BiliLoadFailedBinder.onCreateViewHolder(BiliLoadFailedBinder.java:43)
                                                                  at com.bilibili.widget.adapter.binder.BiliLoadFailedBinder.onCreateViewHolder(BiliLoadFailedBinder.java:23)
                                                                  at com.common.widget.adapter.DefaultAdapterWrapper.onCreateViewHolder(DefaultAdapterWrapper.java:134)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
                                                                  at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
                                                                  at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
                                                                  at android.view.View.layout(View.java:16636)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                  at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
                                                                  at android.view.View.layout(View.java:16636)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
                                                                  at android.view.View.layout(View.java:16636)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                  at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                                                                  at android.view.View.layout(View.java:16636)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                  at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
                                                                  at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
                                                                  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
                                                                  at android.view.View.layout(View.java:16636)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                  at android.view.View.layout(View.java:16636)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                  at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
                                                                  at android.view.View.layout(View.java:16636)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                  at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
                                                              	at android.view.View.lay

**Comment by miserydx** [comment]
已修复，是因为引用了错误的布局文件

**Comment by luxiao0314** [comment]
java.net.ConnectException: Failed to connect to /192.168.255.170:8080
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:225)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at com.bilibili.di.module.ApiModule$1.intercept(ApiModule.java:183)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.RealCall.execute(RealCall.java:69)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by luxiao0314** [comment]
java.net.ConnectException: Failed to connect to /192.168.255.170:8080
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:225)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.061 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at com.bilibili.di.module.ApiModule$1.intercept(ApiModule.java:183)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
03-16 10:40:13.062 9398-9398/com.bilibili W/System.err:     at okhttp3.RealCall.execute(RealCall.java:69)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-16 10:40:13.063 9398-9398/com.bilibili W/System.err:     at java.lang.Thread.run(Thread.java:818)
